<?php

function dumpstamp_menu() {
  $items['dumpstamp'] = array(
    'title' => 'Dump Stamp',
    'access callback' => TRUE,
    'page callback' => 'dumpstamp_page',
  );
  $items['dumpstamp/%name'] = array(
    'page callback' => 'dumpstamp_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'title' => 'Dump Stamp with a Name',
  );

  return $items;
}

function dumpstamp_page($name = 'Rick') {
  $message = t('Dumpstamp with name');
  
  $page = array(
    '#markup' => "$message: $name",
  );

  return $page;
}

